# build th# e sort-mtx executable, that will be used to sort matrix elements (by row and by column)
# g++ -Wall -O# 3 sort-mtx.cpp -# o sort-mtx

wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/ncvxqp1.tar.gz; mkdir -p GHS_indef; mv ncvxqp1.tar.gz GHS_indef/; cd GHS_indef/; tar -xvf ncvxqp1.tar.gz; mv ncvxqp1/ncvxqp1.mtx ../; rm -rf ncvxqp1 ncvxqp1.tar.gz; cd ../; rm -rf GHS_indef; # ./sort-mtx ncvxqp1.mtx ncvxqp1.sorted.mtx; mv ncvxqp1.sorted.mtx ncvxqp1.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/aug2d.tar.gz; mkdir -p GHS_indef; mv aug2d.tar.gz GHS_indef/; cd GHS_indef/; tar -xvf aug2d.tar.gz; mv aug2d/aug2d.mtx ../; rm -rf aug2d aug2d.tar.gz; cd ../; rm -rf GHS_indef; # ./sort-mtx aug2d.mtx aug2d.sorted.mtx; mv aug2d.sorted.mtx aug2d.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/QY/case9.tar.gz; mkdir -p QY; mv case9.tar.gz QY/; cd QY/; tar -xvf case9.tar.gz; mv case9/case9.mtx ../; rm -rf case9 case9.tar.gz; cd ../; rm -rf QY; # ./sort-mtx case9.mtx case9.sorted.mtx; mv case9.sorted.mtx case9.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n16.tar.gz; mkdir -p DIMACS10; mv delaunay_n16.tar.gz DIMACS10/; cd DIMACS10/; tar -xvf delaunay_n16.tar.gz; mv delaunay_n16/delaunay_n16.mtx ../; rm -rf delaunay_n16 delaunay_n16.tar.gz; cd ../; rm -rf DIMACS10; # ./sort-mtx delaunay_n16.mtx delaunay_n16.sorted.mtx; mv delaunay_n16.sorted.mtx delaunay_n16.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-9-b3.tar.gz; mkdir -p JGD_Homology; mv ch7-9-b3.tar.gz JGD_Homology/; cd JGD_Homology/; tar -xvf ch7-9-b3.tar.gz; mv ch7-9-b3/ch7-9-b3.mtx ../; rm -rf ch7-9-b3 ch7-9-b3.tar.gz; cd ../; rm -rf JGD_Homology; # ./sort-mtx ch7-9-b3.mtx ch7-9-b3.sorted.mtx; mv ch7-9-b3.sorted.mtx ch7-9-b3.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Pothen/tandem_dual.tar.gz; mkdir -p Pothen; mv tandem_dual.tar.gz Pothen/; cd Pothen/; tar -xvf tandem_dual.tar.gz; mv tandem_dual/tandem_dual.mtx ../; rm -rf tandem_dual tandem_dual.tar.gz; cd ../; rm -rf Pothen; # ./sort-mtx tandem_dual.mtx tandem_dual.sorted.mtx; mv tandem_dual.sorted.mtx tandem_dual.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Averous/epb3.tar.gz; mkdir -p Averous; mv epb3.tar.gz Averous/; cd Averous/; tar -xvf epb3.tar.gz; mv epb3/epb3.mtx ../; rm -rf epb3 epb3.tar.gz; cd ../; rm -rf Averous; # ./sort-mtx epb3.mtx epb3.sorted.mtx; mv epb3.sorted.mtx epb3.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch8-8-b3.tar.gz; mkdir -p JGD_Homology; mv ch8-8-b3.tar.gz JGD_Homology/; cd JGD_Homology/; tar -xvf ch8-8-b3.tar.gz; mv ch8-8-b3/ch8-8-b3.mtx ../; rm -rf ch8-8-b3 ch8-8-b3.tar.gz; cd ../; rm -rf JGD_Homology; # ./sort-mtx ch8-8-b3.mtx ch8-8-b3.sorted.mtx; mv ch8-8-b3.sorted.mtx ch8-8-b3.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/vanHeukelum/cage11.tar.gz; mkdir -p vanHeukelum; mv cage11.tar.gz vanHeukelum/; cd vanHeukelum/; tar -xvf cage11.tar.gz; mv cage11/cage11.mtx ../; rm -rf cage11 cage11.tar.gz; cd ../; rm -rf vanHeukelum; # ./sort-mtx cage11.mtx cage11.sorted.mtx; mv cage11.sorted.mtx cage11.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Si5H12.tar.gz; mkdir -p PARSEC; mv Si5H12.tar.gz PARSEC/; cd PARSEC/; tar -xvf Si5H12.tar.gz; mv Si5H12/Si5H12.mtx ../; rm -rf Si5H12 Si5H12.tar.gz; cd ../; rm -rf PARSEC; # ./sort-mtx Si5H12.mtx Si5H12.sorted.mtx; mv Si5H12.sorted.mtx Si5H12.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Nemeth/nemeth19.tar.gz; mkdir -p Nemeth; mv nemeth19.tar.gz Nemeth/; cd Nemeth/; tar -xvf nemeth19.tar.gz; mv nemeth19/nemeth19.mtx ../; rm -rf nemeth19 nemeth19.tar.gz; cd ../; rm -rf Nemeth; # ./sort-mtx nemeth19.mtx nemeth19.sorted.mtx; mv nemeth19.sorted.mtx nemeth19.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/TKK/tube1.tar.gz; mkdir -p TKK; mv tube1.tar.gz TKK/; cd TKK/; tar -xvf tube1.tar.gz; mv tube1/tube1.mtx ../; rm -rf tube1 tube1.tar.gz; cd ../; rm -rf TKK; # ./sort-mtx tube1.mtx tube1.sorted.mtx; mv tube1.sorted.mtx tube1.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Kim/kim1.tar.gz; mkdir -p Kim; mv kim1.tar.gz Kim/; cd Kim/; tar -xvf kim1.tar.gz; mv kim1/kim1.mtx ../; rm -rf kim1 kim1.tar.gz; cd ../; rm -rf Kim; # ./sort-mtx kim1.mtx kim1.sorted.mtx; mv kim1.sorted.mtx kim1.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMSDS/2D_54019_highK.tar.gz; mkdir -p Schenk_IBMSDS; mv 2D_54019_highK.tar.gz Schenk_IBMSDS/; cd Schenk_IBMSDS/; tar -xvf 2D_54019_highK.tar.gz; mv 2D_54019_highK/2D_54019_highK.mtx ../; rm -rf 2D_54019_highK 2D_54019_highK.tar.gz; cd ../; rm -rf Schenk_IBMSDS; # ./sort-mtx 2D_54019_highK.mtx 2D_54019_highK.sorted.mtx; mv 2D_54019_highK.sorted.mtx 2D_54019_highK.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Nemeth/nemeth21.tar.gz; mkdir -p Nemeth; mv nemeth21.tar.gz Nemeth/; cd Nemeth/; tar -xvf nemeth21.tar.gz; mv nemeth21/nemeth21.mtx ../; rm -rf nemeth21 nemeth21.tar.gz; cd ../; rm -rf Nemeth; # ./sort-mtx nemeth21.mtx nemeth21.sorted.mtx; mv nemeth21.sorted.mtx nemeth21.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Nemeth/nemeth22.tar.gz; mkdir -p Nemeth; mv nemeth22.tar.gz Nemeth/; cd Nemeth/; tar -xvf nemeth22.tar.gz; mv nemeth22/nemeth22.mtx ../; rm -rf nemeth22 nemeth22.tar.gz; cd ../; rm -rf Nemeth; # ./sort-mtx nemeth22.mtx nemeth22.sorted.mtx; mv nemeth22.sorted.mtx nemeth22.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Nemeth/nemeth23.tar.gz; mkdir -p Nemeth; mv nemeth23.tar.gz Nemeth/; cd Nemeth/; tar -xvf nemeth23.tar.gz; mv nemeth23/nemeth23.mtx ../; rm -rf nemeth23 nemeth23.tar.gz; cd ../; rm -rf Nemeth; # ./sort-mtx nemeth23.mtx nemeth23.sorted.mtx; mv nemeth23.sorted.mtx nemeth23.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Hamrle/Hamrle3.tar.gz; mkdir -p Hamrle; mv Hamrle3.tar.gz Hamrle/; cd Hamrle/; tar -xvf Hamrle3.tar.gz; mv Hamrle3/Hamrle3.mtx ../; rm -rf Hamrle3 Hamrle3.tar.gz; cd ../; rm -rf Hamrle; # ./sort-mtx Hamrle3.mtx Hamrle3.sorted.mtx; mv Hamrle3.sorted.mtx Hamrle3.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/ATandT/pre2.tar.gz; mkdir -p ATandT; mv pre2.tar.gz ATandT/; cd ATandT/; tar -xvf pre2.tar.gz; mv pre2/pre2.mtx ../; rm -rf pre2 pre2.tar.gz; cd ../; rm -rf ATandT; # ./sort-mtx pre2.mtx pre2.sorted.mtx; mv pre2.sorted.mtx pre2.mtx
wget https://suitesparse-collection-website.herokuapp.com/MM/Chen/pkustk14.tar.gz; mkdir -p Chen; mv pkustk14.tar.gz Chen/; cd Chen/; tar -xvf pkustk14.tar.gz; mv pkustk14/pkustk14.mtx ../; rm -rf pkustk14 pkustk14.tar.gz; cd ../; rm -rf Chen; # ./sort-mtx pkustk14.mtx pkustk14.sorted.mtx; mv pkustk14.sorted.mtx pkustk14.mtx
